#!/usr/bin/env bash
# ============================================================================
# autosize.sh — derive ALL container resource limits from the ACTUAL host.
# ============================================================================
# Goal: Scouter adapts to whatever machine it runs on. No hand-tuning when you
# change CPU or RAM. Run it once before `docker compose up` (start.sh does this
# for you) and re-run it whenever the host changes — the numbers recompute.
#
# What it sizes (all as fractions of the detected RAM, with sane floors):
#   *_MEM_LIMIT          — per-container memory cap (the cgroup memory.max that
#                          ClickHouse / the Go crawler self-detect to bound
#                          THEIR own heap; also the kernel's runaway safety net).
# What it derives from CPU cores:
#   MAX_CONCURRENT_CRAWLS / MAX_CONCURRENT_PAGES / PAGE_POOL_SIZE / …
#
# It does NOT set CPU quotas: the compose files use cpu_shares (relative weights)
# which already adapt to any core count and never over-subscribe, plus the Go
# crawler's PSI/AIMD governor throttles fetches on real CPU pressure. So CPU is
# adaptive without any machine-specific constant.
#
# Output: a key=value file (default .env.autosize) that start.sh sources into
# the environment before `docker compose up`, so compose interpolates ${VAR}.
# ============================================================================
set -u

OUT="${1:-.env.autosize}"

# --- clamp value lo hi(0 = no upper bound) ---------------------------------
clamp() {
  local v=$1 lo=$2 hi=$3
  if [ "$v" -lt "$lo" ]; then v=$lo; fi
  if [ "$hi" -gt 0 ] && [ "$v" -gt "$hi" ]; then v=$hi; fi
  echo "$v"
}

# --- Detect the host (override with AUTOSIZE_CORES / AUTOSIZE_TOTAL_MB to
# simulate another machine, e.g. AUTOSIZE_CORES=4 AUTOSIZE_TOTAL_MB=16384) ----
CORES="${AUTOSIZE_CORES:-$(nproc 2>/dev/null || echo 2)}"
if [ -n "${AUTOSIZE_TOTAL_MB:-}" ]; then
  TOTAL_MB="$AUTOSIZE_TOTAL_MB"
elif [ -r /proc/meminfo ]; then
  TOTAL_MB=$(($(awk '/^MemTotal:/{print $2; exit}' /proc/meminfo) / 1024))
else
  TOTAL_MB=4096 # assume 4 GB if unknown
fi

# --- Reserve headroom for the kernel, page cache and Docker itself ---------
# 18% of RAM, never less than 1536 MB. The container caps below sum to AVAIL,
# so even if every container hit its cap at once the host keeps this slack and
# the OOM-killer can't be driven into a restart loop.
RESERVE_MB=$((TOTAL_MB * 18 / 100))
[ "$RESERVE_MB" -lt 1536 ] && RESERVE_MB=1536
AVAIL_MB=$((TOTAL_MB - RESERVE_MB))
[ "$AVAIL_MB" -lt 2048 ] && AVAIL_MB=2048 # extreme-small-box floor

# --- Memory budget by weight (interactive + storage first) -----------------
# Weights are a share of AVAIL; floors guarantee each service can still boot on
# a tiny box. ClickHouse self-caps max_server_memory_usage to ~90% of its cap;
# the Go crawler sets GOMEMLIMIT to ~90% of its cap.
CH=$(clamp $((AVAIL_MB * 30 / 100)) 1024 0)  # ClickHouse — heaviest
PG=$(clamp $((AVAIL_MB * 13 / 100)) 512 0)   # Postgres (frontier + metadata)
APP=$(clamp $((AVAIL_MB * 9 / 100)) 512 0)   # PHP app (UI + API)
CR=$(clamp $((AVAIL_MB * 14 / 100)) 768 0)   # Go crawler
REND_TOTAL=$((AVAIL_MB * 20 / 100))          # 3 renderers share this
WORK_TOTAL=$((AVAIL_MB * 10 / 100))          # 4 PHP workers share this
MCP=256                                      # tiny adapter, fixed

REND=$(clamp $((REND_TOTAL / 3)) 384 0)
WORK=$(clamp $((WORK_TOTAL / 4)) 256 0)

# --- Throughput knobs derived from cores -----------------------------------
# Simultaneous crawls scale with cores (the PSI governor handles per-fetch
# concurrency on top of this, so this is a coarse ceiling, not a tight tune).
CRAWLS=$(clamp $((CORES * 3 / 4)) 2 10)
CURL=12
POOL=8
# Chrome pages per renderer: bounded by BOTH cores and the renderer's RAM share
# (~40 MB/page on top of a ~200 MB Chrome base).
PAGES=$(clamp $((CORES * 2)) 4 24)
PAGES_BY_RAM=$(((REND - 200) / 40))
[ "$PAGES_BY_RAM" -lt 4 ] && PAGES_BY_RAM=4
[ "$PAGES" -gt "$PAGES_BY_RAM" ] && PAGES=$PAGES_BY_RAM

cat >"$OUT" <<EOF
# ---------------------------------------------------------------------------
# GENERATED by scripts/autosize.sh — DO NOT edit by hand.
# Host detected: ${CORES} cores, ${TOTAL_MB} MB RAM (reserved ${RESERVE_MB} MB for the host).
# Re-run scripts/autosize.sh after changing the machine's CPU or RAM.
# ---------------------------------------------------------------------------
POSTGRES_MEM_LIMIT=${PG}m
CLICKHOUSE_MEM_LIMIT=${CH}m
SCOUTER_MEM_LIMIT=${APP}m
MCP_MEM_LIMIT=${MCP}m
WORKER_MEM_LIMIT=${WORK}m
CRAWLER_MEM_LIMIT=${CR}m
RENDERER_MEM_LIMIT=${REND}m
MAX_CONCURRENT_CRAWLS=${CRAWLS}
MAX_CONCURRENT_CURL=${CURL}
POOL_CONNS_PER_CRAWL=${POOL}
MAX_CONCURRENT_PAGES=${PAGES}
PAGE_POOL_SIZE=${PAGES}
EOF

COMMITTED=$((CH + PG + APP + CR + REND * 3 + WORK * 4 + MCP))

echo "autosize → ${CORES} cores / ${TOTAL_MB} MB"
echo "  mem: CH=${CH}m PG=${PG}m app=${APP}m crawler=${CR}m renderer=${REND}m×3 worker=${WORK}m×4 mcp=${MCP}m"
echo "  throughput: crawls=${CRAWLS} pages/renderer=${PAGES} curl=${CURL}"
echo "  committed caps: ${COMMITTED} MB of ${TOTAL_MB} MB"
echo "  written to ${OUT}"
if [ "$COMMITTED" -gt "$TOTAL_MB" ]; then
  echo "  WARNING: the per-service floors sum above this host's RAM — it is below"
  echo "  the realistic minimum for the full stack. Consider fewer renderers/workers"
  echo "  or a bigger box (>= 8 GB recommended)." >&2
fi
